name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/include/lint.yml
    permissions:
      packages: read

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # The following step is a failsafe to ensure that binaries are available
      - name: Add node_modules/.bin to PATH
        run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - name: Build
        run: bun run build
